"""Dados de seed: estados, partidos, federações, eleições, institutos."""
from datetime import date

ESTADOS = [
    # (sigla, nome, regiao, populacao, eleitorado, capital, codigo_ibge)
    ("AC", "Acre", "norte", 906876, 619072, "Rio Branco", 12),
    ("AL", "Alagoas", "nordeste", 3365351, 2294388, "Maceió", 27),
    ("AM", "Amazonas", "norte", 4269995, 2715637, "Manaus", 13),
    ("AP", "Amapá", "norte", 877613, 539968, "Macapá", 16),
    ("BA", "Bahia", "nordeste", 14985284, 11116994, "Salvador", 29),
    ("CE", "Ceará", "nordeste", 9240580, 6814717, "Fortaleza", 23),
    ("DF", "Distrito Federal", "centro_oeste", 2982818, 2129275, "Brasília", 53),
    ("ES", "Espírito Santo", "sudeste", 4108508, 2837557, "Vitória", 32),
    ("GO", "Goiás", "centro_oeste", 7206589, 5076124, "Goiânia", 52),
    ("MA", "Maranhão", "nordeste", 7153262, 4974395, "São Luís", 21),
    ("MG", "Minas Gerais", "sudeste", 21411923, 16207181, "Belo Horizonte", 31),
    ("MS", "Mato Grosso do Sul", "centro_oeste", 2839188, 1990811, "Campo Grande", 50),
    ("MT", "Mato Grosso", "centro_oeste", 3567234, 2447137, "Cuiabá", 51),
    ("PA", "Pará", "norte", 8777124, 5739867, "Belém", 15),
    ("PB", "Paraíba", "nordeste", 4039277, 3037067, "João Pessoa", 25),
    ("PE", "Pernambuco", "nordeste", 9674793, 6927643, "Recife", 26),
    ("PI", "Piauí", "nordeste", 3289290, 2474443, "Teresina", 22),
    ("PR", "Paraná", "sul", 11597484, 8378415, "Curitiba", 41),
    ("RJ", "Rio de Janeiro", "sudeste", 17463349, 12832348, "Rio de Janeiro", 33),
    ("RN", "Rio Grande do Norte", "nordeste", 3560903, 2535396, "Natal", 24),
    ("RO", "Rondônia", "norte", 1815278, 1248569, "Porto Velho", 11),
    ("RR", "Roraima", "norte", 652713, 365869, "Boa Vista", 14),
    ("RS", "Rio Grande do Sul", "sul", 11422973, 8517043, "Porto Alegre", 43),
    ("SC", "Santa Catarina", "sul", 7762154, 5701128, "Florianópolis", 42),
    ("SE", "Sergipe", "nordeste", 2318822, 1648203, "Aracaju", 28),
    ("SP", "São Paulo", "sudeste", 46649132, 34642996, "São Paulo", 35),
    ("TO", "Tocantins", "norte", 1607363, 1063776, "Palmas", 17),
]

PARTIDOS = [
    # (sigla, nome, numero, espectro, espectro_econ, espectro_social, cor)
    ("PT", "Partido dos Trabalhadores", 13, "esquerda", "estatista", "progressista", "#C8102E"),
    ("PCdoB", "Partido Comunista do Brasil", 65, "esquerda", "estatista", "progressista", "#A30A0C"),
    ("PV", "Partido Verde", 43, "centro_esquerda", "intervencionista", "progressista", "#5BA84F"),
    ("PSOL", "Partido Socialismo e Liberdade", 50, "extrema_esquerda", "estatista", "progressista", "#F5A623"),
    ("REDE", "Rede Sustentabilidade", 18, "centro_esquerda", "intervencionista", "progressista", "#1E9F77"),
    ("PSB", "Partido Socialista Brasileiro", 40, "centro_esquerda", "intervencionista", "progressista", "#FFCD00"),
    ("PDT", "Partido Democrático Trabalhista", 12, "centro_esquerda", "intervencionista", "moderado", "#E60026"),
    ("SOLIDARIEDADE", "Solidariedade", 77, "centro", "intervencionista", "moderado", "#FF6E00"),
    ("MDB", "Movimento Democrático Brasileiro", 15, "centro", "intervencionista", "moderado", "#0C3E6A"),
    ("CIDADANIA", "Cidadania", 23, "centro", "liberal", "moderado", "#EF4136"),
    ("PSD", "Partido Social Democrático", 55, "centro", "liberal", "moderado", "#F58220"),
    ("AVANTE", "Avante", 70, "centro", "intervencionista", "moderado", "#0099CC"),
    ("PODE", "Podemos", 20, "centro_direita", "liberal", "moderado", "#1A87C2"),
    ("PSDB", "Partido da Social Democracia Brasileira", 45, "centro_direita", "liberal", "moderado", "#0093DD"),
    ("UNIAO", "União Brasil", 44, "centro_direita", "liberal", "conservador", "#003D8F"),
    ("REPUBLICANOS", "Republicanos", 10, "direita", "liberal", "conservador", "#005FA3"),
    ("PP", "Progressistas", 11, "direita", "liberal", "conservador", "#0067B3"),
    ("PL", "Partido Liberal", 22, "direita", "ultra_liberal", "conservador", "#1F4E80"),
    ("NOVO", "Partido Novo", 30, "direita", "ultra_liberal", "moderado", "#F39200"),
    ("PRTB", "Partido Renovador Trabalhista Brasileiro", 28, "direita", "liberal", "conservador", "#FFA500"),
    ("DC", "Democracia Cristã", 27, "direita", "liberal", "ultra_conservador", "#006400"),
    ("PMB", "Partido da Mulher Brasileira", 35, "centro", "intervencionista", "moderado", "#E91E63"),
    ("AGIR", "Agir", 36, "centro", "intervencionista", "moderado", "#7B1FA2"),
    ("MOBILIZA", "Mobiliza", 33, "centro", "intervencionista", "moderado", "#03A9F4"),
    ("PRD", "Partido Renovação Democrática", 25, "centro_direita", "liberal", "moderado", "#FF5722"),
    ("UP", "Unidade Popular", 80, "extrema_esquerda", "estatista", "progressista", "#B71C1C"),
    ("PCB", "Partido Comunista Brasileiro", 21, "extrema_esquerda", "estatista", "progressista", "#8B0000"),
    ("PCO", "Partido da Causa Operária", 29, "extrema_esquerda", "estatista", "progressista", "#D32F2F"),
    ("PSTU", "Partido Socialista dos Trabalhadores Unificado", 16, "extrema_esquerda", "estatista", "progressista", "#9F1212"),
]

# Federação Brasil da Esperança (PT, PCdoB, PV)
FEDERACOES = [
    {
        "nome": "Federação Brasil da Esperança",
        "sigla": "FE Brasil",
        "partidos_siglas": ["PT", "PCdoB", "PV"],
        "inicio_vigencia": date(2022, 4, 1),
        "numero_legenda": 13,
    },
    {
        "nome": "Federação PSOL-REDE",
        "sigla": "PSOL-REDE",
        "partidos_siglas": ["PSOL", "REDE"],
        "inicio_vigencia": date(2022, 5, 1),
        "numero_legenda": 50,
    },
    {
        "nome": "Federação PSDB-Cidadania",
        "sigla": "PSDB-Cidadania",
        "partidos_siglas": ["PSDB", "CIDADANIA"],
        "inicio_vigencia": date(2022, 5, 1),
        "numero_legenda": 45,
    },
]

ELEICOES = [
    {"ano": 2002, "turno": 1, "tipo": "estadual_geral", "data": date(2002, 10, 6)},
    {"ano": 2002, "turno": 2, "tipo": "estadual_geral", "data": date(2002, 10, 27)},
    {"ano": 2006, "turno": 1, "tipo": "estadual_geral", "data": date(2006, 10, 1)},
    {"ano": 2006, "turno": 2, "tipo": "estadual_geral", "data": date(2006, 10, 29)},
    {"ano": 2010, "turno": 1, "tipo": "estadual_geral", "data": date(2010, 10, 3)},
    {"ano": 2010, "turno": 2, "tipo": "estadual_geral", "data": date(2010, 10, 31)},
    {"ano": 2014, "turno": 1, "tipo": "estadual_geral", "data": date(2014, 10, 5)},
    {"ano": 2014, "turno": 2, "tipo": "estadual_geral", "data": date(2014, 10, 26)},
    {"ano": 2018, "turno": 1, "tipo": "estadual_geral", "data": date(2018, 10, 7)},
    {"ano": 2018, "turno": 2, "tipo": "estadual_geral", "data": date(2018, 10, 28)},
    {"ano": 2022, "turno": 1, "tipo": "estadual_geral", "data": date(2022, 10, 2)},
    {"ano": 2022, "turno": 2, "tipo": "estadual_geral", "data": date(2022, 10, 30)},
    {"ano": 2024, "turno": 1, "tipo": "municipal", "data": date(2024, 10, 6)},
    {"ano": 2024, "turno": 2, "tipo": "municipal", "data": date(2024, 10, 27)},
    {"ano": 2026, "turno": 1, "tipo": "estadual_geral", "data": date(2026, 10, 4)},
    {"ano": 2026, "turno": 2, "tipo": "estadual_geral", "data": date(2026, 10, 25)},
]

INSTITUTOS = [
    ("Datafolha", "Datafolha", "https://datafolha.folha.uol.com.br", 5),
    ("Quaest", "Quaest", "https://quaest.com.br", 5),
    ("Ipec", "Ipec", "https://www.ipec-inteligencia.com.br", 5),
    ("AtlasIntel", "AtlasIntel", "https://atlasintel.org", 4),
    ("Paraná Pesquisas", "ParanáPesquisas", "https://paranapesquisas.com.br", 4),
    ("Real Time Big Data", "RealTimeBD", "https://www.realtimebigdata.com.br", 4),
    ("Genial/Quaest", "Genial/Quaest", "", 4),
    ("Futura Inteligência", "Futura", "https://futurainteligencia.com.br", 3),
    ("Ranking Pesquisa", "Ranking", "", 3),
    ("Veritá Brasil", "Veritá", "", 3),
    ("Idéia Big Data", "Idéia", "", 3),
    ("Vox Populi", "VoxPopuli", "", 3),
    ("CNT/MDA", "CNT/MDA", "", 3),
]

# Fontes RSS NACIONAIS — generalistas + agências
FONTES_NACIONAIS = [
    # (nome, url_feed, url_site, tipo, abrangencia, espectro, conf, peso, freq_min)
    ("G1 Política", "https://g1.globo.com/rss/g1/politica/", "https://g1.globo.com/politica/", "jornal_nacional", "nacional", "centro", 5, 5, 30),
    ("Folha - Poder", "https://feeds.folha.uol.com.br/poder/rss091.xml", "https://www.folha.uol.com.br/poder", "jornal_nacional", "nacional", "centro", 5, 5, 30),
    ("UOL Política", "https://rss.uol.com.br/feed/politica.xml", "https://noticias.uol.com.br/politica", "jornal_nacional", "nacional", "centro", 5, 4, 30),
    ("CNN Brasil Política", "https://www.cnnbrasil.com.br/politica/feed/", "https://www.cnnbrasil.com.br/politica", "jornal_nacional", "nacional", "centro", 4, 4, 30),
    ("Poder360", "https://www.poder360.com.br/feed/", "https://www.poder360.com.br", "portal", "nacional", "centro", 5, 5, 30),
    ("Congresso em Foco", "https://congressoemfoco.uol.com.br/feed/", "https://congressoemfoco.uol.com.br", "portal", "nacional", "centro", 4, 5, 60),
    ("Brasil 247", "https://www.brasil247.com/rss", "https://www.brasil247.com", "portal", "nacional", "esquerda", 3, 3, 60),
    ("Carta Capital", "https://www.cartacapital.com.br/feed/", "https://www.cartacapital.com.br", "portal", "nacional", "centro_esquerda", 4, 4, 60),
    ("Agência Pública", "https://apublica.org/feed/", "https://apublica.org", "agencia", "nacional", "centro_esquerda", 5, 4, 120),
    ("Intercept Brasil", "https://www.intercept.com.br/feed/", "https://www.intercept.com.br", "portal", "nacional", "esquerda", 4, 4, 120),
    ("Agência Brasil", "https://agenciabrasil.ebc.com.br/rss/politica/feed.xml", "https://agenciabrasil.ebc.com.br/politica", "agencia", "nacional", "tecnico", 5, 5, 30),
    ("Agência Câmara", "https://www.camara.leg.br/noticias/rss/0", "https://www.camara.leg.br/noticias", "agencia", "nacional", "tecnico", 5, 5, 30),
    ("Agência Senado", "https://www12.senado.leg.br/noticias/rss/feed-noticias", "https://www12.senado.leg.br/noticias", "agencia", "nacional", "tecnico", 5, 5, 30),
]

# Fontes RSS ESTADUAIS — 81 jornais (3 por estado), do arquivo Guia de Mídia (29/04/2026)
# (sigla_uf, nome, url_feed, url_site)
FONTES_ESTADUAIS = [
    ("AC", "A Gazeta do Acre", "https://agazetadoacre.com/feed/", "https://agazetadoacre.com/"),
    ("AC", "PáginaNet", "https://paginanet.com.br/feed/", "https://paginanet.com.br/"),
    ("AC", "Jornal Opinião", "https://jornalopiniao.net/feed/", "https://jornalopiniao.net/"),
    ("AL", "Gazeta de Alagoas", "https://www.gazetadealagoas.com.br/feed", "https://www.gazetadealagoas.com.br/"),
    ("AL", "O Jornal Extra", "https://ojornalextra.com.br/feed", "https://ojornalextra.com.br/"),
    ("AL", "Primeira Edição", "https://primeiraedicao.com.br/feed/", "https://primeiraedicao.com.br/"),
    ("AP", "Diário do Amapá", "https://www.diariodoamapa.com.br/feed", "https://www.diariodoamapa.com.br/"),
    ("AP", "Folha do Amapá", "https://www.folhadoamapa.com/feed", "https://www.folhadoamapa.com/"),
    ("AP", "Guia Macapá", "https://guia.macapa.br/feed", "https://guia.macapa.br/"),
    ("AM", "No Amazonas é Assim", "https://noamazonaseassim.com/feed/", "https://noamazonaseassim.com/"),
    ("AM", "Em Tempo", "https://emtempo.com.br/feed", "https://emtempo.com.br/"),
    ("AM", "Jornal Agora (AM)", "https://emtempo.com.br/category/jornal-impresso-agora/feed/", "https://emtempo.com.br/category/jornal-impresso-agora/"),
    ("BA", "Correio da Bahia", "http://www.correio24horas.com.br/rss", "http://www.correio24horas.com.br/"),
    ("BA", "Jornal A Tarde", "https://atarde.com.br/rss", "https://atarde.com.br/"),
    ("BA", "Tribuna da Bahia", "http://www.tribunadabahia.com.br/feed", "http://www.tribunadabahia.com.br/"),
    ("CE", "Diário do Nordeste", "http://www.diariodonordeste.com.br/cmlink/feed-webstories-7.5124750", "http://www.diariodonordeste.com.br/"),
    ("CE", "Jornal O Povo", "https://www.opovo.com.br/rss", "https://www.opovo.com.br/"),
    ("CE", "Portal CN7", "https://cn7.com.br/feed/", "https://cn7.com.br/"),
    ("DF", "Correio Braziliense", "https://www.correiobraziliense.com.br/feed", "https://www.correiobraziliense.com.br/"),
    ("DF", "Jornal de Brasília", "https://jornaldebrasilia.com.br/feed", "https://jornaldebrasilia.com.br/"),
    ("DF", "Jornal Brasília Agora", "https://brasiliaagora.com.br/feed", "https://brasiliaagora.com.br/"),
    ("ES", "A Gazeta", "https://www.agazeta.com.br/rss", "https://www.agazeta.com.br/"),
    ("ES", "Jornal A Tribuna ES", "https://tribunaonline.com.br/rss", "https://www.tribunaonline.com.br/"),
    ("ES", "Jornal ES Hoje", "https://eshoje.com.br/feed/", "https://eshoje.com.br/"),
    ("GO", "Diário da Manhã", "https://www.dm.com.br/feed", "https://www.dm.com.br/"),
    ("GO", "Jornal Opção", "https://www.jornalopcao.com.br/feed/", "https://www.jornalopcao.com.br/"),
    ("GO", "Tribuna do Planalto", "https://tribunadoplanalto.com.br/feed/", "https://tribunadoplanalto.com.br/"),
    ("MA", "Jornal O Imparcial", "https://oimparcial.com.br/feed", "https://oimparcial.com.br/"),
    ("MA", "Jornal Pequeno", "https://jornalpequeno.com.br/feed/", "https://jornalpequeno.com.br/"),
    ("MA", "Jornal O Pedreirense", "https://opedreirense.com.br/feed/", "https://opedreirense.com.br/"),
    ("MT", "Jornal Circuito MT", "https://circuitomt.com.br/feed/", "https://circuitomt.com.br/"),
    ("MT", "Correio de Mato Grosso", "https://correiodematogrosso.com.br/comments/feed/", "https://correiodematogrosso.com.br/"),
    ("MT", "Folha do Mato Grosso", "https://folhadematogrosso.com.br/feed/", "https://folhadematogrosso.com.br/"),
    ("MS", "Jornal de Domingo (JD1)", "https://www.jd1noticias.com/ultimas-noticias/feed", "http://www.jornaldedomingo.com.br/"),
    ("MS", "Jornal O Estado Online", "https://oestadoonline.com.br/feed/", "http://www.oestadoonline.com.br/"),
    ("MS", "Jornal do Ônibus MS", "https://jornaldoonibusms.com.br/feed/", "http://www.jornaldoonibusms.com.br/"),
    ("MG", "Estado de Minas", "https://www.em.com.br/feed", "https://www.em.com.br/"),
    ("MG", "Jornal Aqui", "https://aqui-hom.uai.com.br/feed/", "http://aqui.uai.com.br/"),
    ("MG", "Super Notícia", "http://www.supernoticia.com.br/feed", "http://www.supernoticia.com.br/"),
    ("PR", "Gazeta do Povo", "https://www.gazetadopovo.com.br/feed", "https://www.gazetadopovo.com.br/"),
    ("PR", "Jornal Impacto PR", "https://impactopr.com.br/feed/", "https://www.impactopr.com.br/"),
    ("PR", "Jornal do Ônibus de Curitiba", "https://jornaldoonibusdecuritiba.com.br/feed/", "http://www.jornaldoonibusdecuritiba.com.br/"),
    ("PB", "Jornal da Paraíba", "http://www.jornaldaparaiba.com.br/feed", "http://www.jornaldaparaiba.com.br/"),
    ("PB", "Jornal A União", "https://auniao.pb.gov.br/RSS", "https://auniao.pb.gov.br/"),
    ("PB", "Jornal A Página", "https://www.jornalapagina.com/feed", "https://www.jornalapagina.com/"),
    ("PA", "O Liberal", "https://www.oliberal.com/cmlink/empregos-concursos-1.643778", "https://www.oliberal.com/"),
    ("PA", "Folha de Castanhal", "https://castanhal.para.jor.br/feeds/posts/default", "https://folhadecastanhal.com.br/"),
    ("PA", "Folha do Progresso", "https://news.folhadoprogresso.com.br/feed/", "http://www.folhadoprogresso.com.br/"),
    ("PE", "Jornal do Commércio", "https://jc.uol.com.br/ultimas/rss.xml", "http://www.jconline.com.br/"),
    ("PE", "Jornal Pinzón", "https://pinzon.com.br/feed/", "https://www.pinzon.com.br/"),
    ("PE", "Jornal do Grande Recife", "https://www.jornaldogranderecife.com.br/feeds/posts/default", "http://www.jornaldogranderecife.com.br/"),
    ("PI", "Jornal O Dia", "http://www.portalodia.com/feed", "http://www.portalodia.com/jornal"),
    ("PI", "Tribuna Nordeste", "https://www.tribunadonordeste.com/feeds/posts/default", "https://tribunadonordeste.com/"),
    ("PI", "Folha Atual", "http://folhaatual.com.br/feed", "http://folhaatual.com.br/"),
    ("RN", "Tribuna do Norte", "https://tribunadonorte.com.br/feed/", "http://www.tribunadonorte.com.br/"),
    ("RN", "Agora RN", "https://agorarn.com.br/feed/", "http://www.agorarn.com.br/"),
    ("RN", "Tribuna de Notícias", "https://www.tribunadenoticias.com.br/feeds/posts/default", "http://www.tribunadenoticias.com.br/"),
    ("RS", "Diário Gaúcho", "http://www.diariogaucho.com.br/feed", "http://www.diariogaucho.com.br/"),
    ("RS", "Jornal do Comércio RS", "https://www.jornaldocomercio.com/rss", "https://www.jornaldocomercio.com/"),
    ("RS", "Jornal Já", "https://www.jornalja.com.br/feed/", "https://www.jornalja.com.br/"),
    ("RJ", "Jornal O Globo", "https://oglobo.globo.com/rss/oglobo", "http://www.oglobo.com.br/"),
    ("RJ", "Jornal O Dia (RJ)", "https://odia.ig.com.br/_conteudo/ultimas-noticias/rss.xml", "https://odia.ig.com.br/"),
    ("RJ", "Jornal Extra", "https://extra.globo.com/rss/extra", "http://www.jornalextraonline.com.br/"),
    ("RO", "Correio de Notícia", "https://www.correiodenoticia.com.br/feed", "https://www.correiodenoticia.com.br/"),
    ("RO", "Jornal Madeirão", "https://madeiraoweb.com.br/feed", "https://madeiraoweb.com.br/"),
    ("RO", "Jornal O Nortão", "https://www.onortao.com.br/feeds/posts/default", "https://www.onortao.com.br/"),
    ("RR", "Jornal O Painel", "https://www.jornalopainel.com/feed/", "https://www.jornalopainel.com/"),
    ("RR", "Jornal Roraima Hoje", "https://www.jornalroraimahoje.com.br/comments/feed/", "https://www.jornalroraimahoje.com.br/"),
    ("RR", "Roraima em Tempo", "https://roraimaemtempo.com.br/feed/", "https://roraimaemtempo.com.br/"),
    ("SC", "Diário Catarinense", "http://www.diariocatarinense.com.br/feed", "http://www.diariocatarinense.com.br/"),
    ("SC", "ND Mais", "https://ndmais.com.br/feed/", "https://ndmais.com.br/"),
    ("SC", "Folha Norte da Ilha", "https://folhanortedailha.com.br/feed/", "https://folhanortedailha.com.br/"),
    ("SE", "Jornal Cinform", "https://cinformonline.com.br/feed/", "https://cinformonline.com.br/"),
    ("SE", "Jornal de Sergipe", "https://jornaldesergipe.com.br/feed", "http://www.jornaldesergipe.com.br/"),
    ("SE", "Correio de Sergipe", "http://ajn1.com.br/feed", "http://ajn1.com.br/"),
    ("SP", "Folha de São Paulo", "https://www1.folha.uol.com.br/feed", "https://www1.folha.uol.com.br/fsp/"),
    ("SP", "O Estado de São Paulo", "https://www.estadao.com.br/arc/outboundfeeds/feeds/rss/sections/geral/?body=%7B%22layout%22:%22google-news%22%7D", "https://www.estadao.com.br/"),
    ("SP", "Agora São Paulo", "http://www.agora.com.br/feed", "http://www.agora.com.br/"),
    ("TO", "Conexão Tocantins", "https://conexaoto.com.br/feed/", "https://conexaoto.com.br/"),
    ("TO", "Jornal Agora Tocantins", "https://www.agora-to.com.br/feed", "https://www.agora-to.com.br/"),
    ("TO", "Jornal Folha Capital", "https://folhacapital.com.br/feed/", "https://www.folhacapital.com.br/"),
]
